# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/Frank/PycharmProjects/EE-Book/src/gui/dialogs/scheduler.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(834, 749)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../iconmonstr/download.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(Dialog)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 540, 718))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.detail_box = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.detail_box.setObjectName(_fromUtf8("detail_box"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.blurb = QtGui.QLabel(self.tab)
        self.blurb.setWordWrap(True)
        self.blurb.setOpenExternalLinks(True)
        self.blurb.setObjectName(_fromUtf8("blurb"))
        self.verticalLayout.addWidget(self.blurb)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.schedule = QtGui.QCheckBox(self.frame)
        self.schedule.setObjectName(_fromUtf8("schedule"))
        self.verticalLayout_2.addWidget(self.schedule)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.days_of_week = QtGui.QRadioButton(self.frame)
        self.days_of_week.setObjectName(_fromUtf8("days_of_week"))
        self.horizontalLayout.addWidget(self.days_of_week)
        self.days_of_month = QtGui.QRadioButton(self.frame)
        self.days_of_month.setObjectName(_fromUtf8("days_of_month"))
        self.horizontalLayout.addWidget(self.days_of_month)
        self.every_x_days = QtGui.QRadioButton(self.frame)
        self.every_x_days.setObjectName(_fromUtf8("every_x_days"))
        self.horizontalLayout.addWidget(self.every_x_days)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.schedule_stack = QtGui.QStackedWidget(self.frame)
        self.schedule_stack.setMaximumSize(QtCore.QSize(16777215, 75))
        self.schedule_stack.setObjectName(_fromUtf8("schedule_stack"))
        self.verticalLayout_2.addWidget(self.schedule_stack)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.frame)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.last_downloaded = QtGui.QLabel(self.frame)
        self.last_downloaded.setText(_fromUtf8(""))
        self.last_downloaded.setWordWrap(True)
        self.last_downloaded.setObjectName(_fromUtf8("last_downloaded"))
        self.verticalLayout_2.addWidget(self.last_downloaded)
        self.verticalLayout.addWidget(self.frame)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.account = QtGui.QGroupBox(self.tab)
        self.account.setObjectName(_fromUtf8("account"))
        self.gridLayout_2 = QtGui.QGridLayout(self.account)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.username = QtGui.QLineEdit(self.account)
        self.username.setObjectName(_fromUtf8("username"))
        self.gridLayout_2.addWidget(self.username, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.account)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.account)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.password = QtGui.QLineEdit(self.account)
        self.password.setEchoMode(QtGui.QLineEdit.Password)
        self.password.setObjectName(_fromUtf8("password"))
        self.gridLayout_2.addWidget(self.password, 1, 1, 1, 1)
        self.show_password = QtGui.QCheckBox(self.account)
        self.show_password.setObjectName(_fromUtf8("show_password"))
        self.gridLayout_2.addWidget(self.show_password, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.account)
        self.label = QtGui.QLabel(self.tab)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.detail_box.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.add_title_tag = QtGui.QCheckBox(self.tab_2)
        self.add_title_tag.setObjectName(_fromUtf8("add_title_tag"))
        self.gridLayout_3.addWidget(self.add_title_tag, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 4, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.keep_issues = QtGui.QSpinBox(self.tab_2)
        self.keep_issues.setMaximum(100000)
        self.keep_issues.setObjectName(_fromUtf8("keep_issues"))
        self.gridLayout_3.addWidget(self.keep_issues, 3, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 2)
        self.custom_tags = QtGui.QLineEdit(self.tab_2)
        self.custom_tags.setObjectName(_fromUtf8("custom_tags"))
        self.gridLayout_3.addWidget(self.custom_tags, 1, 2, 1, 1)
        self.detail_box.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.detail_box)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 2, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 3, 1, 1, 1)
        self.count_label = QtGui.QLabel(Dialog)
        self.count_label.setText(_fromUtf8(""))
        self.count_label.setAlignment(QtCore.Qt.AlignCenter)
        self.count_label.setObjectName(_fromUtf8("count_label"))
        self.gridLayout.addWidget(self.count_label, 2, 0, 1, 1)
        self.recipes = QtGui.QTreeView(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recipes.sizePolicy().hasHeightForWidth())
        self.recipes.setSizePolicy(sizePolicy)
        self.recipes.setProperty("showDropIndicator", False)
        self.recipes.setIconSize(QtCore.QSize(16, 16))
        self.recipes.setAnimated(True)
        self.recipes.setHeaderHidden(True)
        self.recipes.setObjectName(_fromUtf8("recipes"))
        self.gridLayout.addWidget(self.recipes, 1, 0, 1, 1)
        self.download_all_button = QtGui.QPushButton(Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/news.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download_all_button.setIcon(icon1)
        self.download_all_button.setObjectName(_fromUtf8("download_all_button"))
        self.gridLayout.addWidget(self.download_all_button, 3, 0, 1, 1)
        self.label_2.setBuddy(self.username)
        self.label_3.setBuddy(self.password)
        self.label_5.setBuddy(self.custom_tags)
        self.label_6.setBuddy(self.keep_issues)

        self.retranslateUi(Dialog)
        self.detail_box.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.add_title_tag, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.keep_issues.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Schedule news download", None))
        self.blurb.setText(_translate("Dialog", "blurb", None))
        self.schedule.setText(_translate("Dialog", "&Schedule for download:", None))
        self.days_of_week.setText(_translate("Dialog", "Days of  week", None))
        self.days_of_month.setText(_translate("Dialog", "Days of month", None))
        self.every_x_days.setText(_translate("Dialog", "Every x days", None))
        self.account.setTitle(_translate("Dialog", "&Account", None))
        self.label_2.setText(_translate("Dialog", "&Username:", None))
        self.label_3.setText(_translate("Dialog", "&Password:", None))
        self.show_password.setText(_translate("Dialog", "&Show password", None))
        self.label.setText(_translate("Dialog", "For the scheduling to work, you must leave calibre running.", None))
        self.detail_box.setTabText(self.detail_box.indexOf(self.tab), _translate("Dialog", "&Schedule", None))
        self.add_title_tag.setText(_translate("Dialog", "Add &title as tag", None))
        self.label_5.setText(_translate("Dialog", "&Extra  tags:", None))
        self.keep_issues.setToolTip(_translate("Dialog", "<p>When set, this option will cause calibre to keep, at most, the specified number of issues of this periodical. Every time a new issue is downloaded, the oldest one is deleted, if the total is larger than this number.\n"
"<p>Note that this feature only works if you have the option to add the title as tag checked, above.\n"
"<p>Also, the setting for deleting periodicals older than a number of days, below, takes priority over this setting.", None))
        self.keep_issues.setSpecialValueText(_translate("Dialog", "all issues", None))
        self.keep_issues.setSuffix(_translate("Dialog", " issues", None))
        self.label_6.setToolTip(_translate("Dialog", "Maximum number of copies (issues) of this recipe to keep.  Set to 0 to keep all (disable).", None))
        self.label_6.setText(_translate("Dialog", "&Keep at most:", None))
        self.detail_box.setTabText(self.detail_box.indexOf(self.tab_2), _translate("Dialog", "&Advanced", None))
        self.download_all_button.setToolTip(_translate("Dialog", "Download all scheduled news sources at once", None))
        self.download_all_button.setText(_translate("Dialog", "Download &all scheduled", None))

import images_rc
